# createuser --superuser root
development:
  adapter: sqlite3
  encoding: utf8
  reconnect: true
  host: localhost
  username: root
  password:
  pool: 5

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: true
  host: localhost
  username: root
  password:
  pool: 5

production:
  adapter: sqlite3
  encoding: utf8
  reconnect: true
  host: localhost
  username: root
  password:
  pool: 5
